### PR TITLE
Element Consolidate

### PR DESCRIPTION
**Pull request by livingshade**
Naively consolidate multiple elements together. For functionality in #25 
- For property
  - Currently I don't analyze on the consolidated element, but use the union of each individually analyzed result, this should give out a conservative result.
- For code gen
  - First consolite the element, and generate mRPC code
- API changes
  - Now `compile_element_property` and `gen_code` accept a list of element names, representing elements to be consolidated. Note that the order of element in the list is the order they will be consolidated. (i.e. acl, logging means putting the logic of acl before that of logging on *requests* side, as if they are attached in that way.)

### CODE REVIEW

**Comment by Kristoff-starling** [comment]
I believe that for now we don't need to implement property inference for consolidated elements, as consolidation is the last step of graph optimization, which means we simply merge adjacent elements and don't need to check the properties :)

**Review by Kristoff-starling — APPROVED** [review]
LGTM! Please feel free to merge it.

**Comment by Romero027** [comment]
This is great! Thanks @livingshade

**Comment by Romero027** [comment]
@Kristoff-starling can you test the compatibility with your graph compiler?

**Comment by Kristoff-starling** [comment]
I have made some simple tests and I believe it works fine.

**Pull request merged**
