### PR TITLE
Update READMEs

### PR DESCRIPTION
**Pull request by Romero027**
First batch of README updates. Mostly cleaning up some old content. 

#15

### CODE REVIEW

**Comment by Romero027** [comment]
I've made some changes to the folder name to make it more informative. 

This might have some implications for your compiler code. cc @livingshade @Kristoff-starling

**Comment by Kristoff-starling** [comment]
LGTM!

**Comment by livingshade** [comment]
Looks to me, but I think it breaks line 37 and line 66 in `compiler/element/__init__.py`, can you update the file path and see if it works?

**Comment by Romero027** [comment]
Ah, fixed

**Comment by livingshade** [comment]
OK, I will merge this.

**Pull request merged**
